sync:
  image: n3llyb0y/wait
  links:
    - rabbitmq
    - websocketd
  environment:
    PORTS: "5672 9502"
    TIMEOUT: "5"

rabbitmq:
  image: rabbitmq
  ports:
    - "5672:5672"

websocketd:
  image: xivo-websocketd-test
  volumes:
    - "./etc/xivo-websocketd:/etc/xivo-websocketd"
    - "./ssl:/usr/local/share/ssl"
  ports:
    - "9502:9502"
  links:
    - rabbitmq
