version: '3'
services:
  sync:
    depends_on:
      - auth
      - mongooseim
      - rabbitmq
      - websocketd
    environment:
      TARGETS: "auth:9497,mongooseim:5222,rabbitmq:5672,websocketd:9502"
