version: '3'
services:
  sync:
    image: wazopbx/wait
    environment:
      TIMEOUT: "15"

  auth:
    image: wazopbx/wazo-auth-mock
    volumes:
      - ./ssl:/usr/local/share/ssl
    ports:
      - "9497"

  rabbitmq:
    image: rabbitmq:3.6.6
    ports:
      - "5672"

  websocketd:
    image: xivo-websocketd-test
    volumes:
      - "../..:/usr/src/xivo-websocketd"
      - "./ssl:/usr/local/share/ssl"
      - "./etc/xivo-websocketd/conf.d/50-base.yml:/etc/xivo-websocketd/conf.d/50-base.yml"
    ports:
      - "9502"
    environment:
      HOME: "/usr/src/xivo-websocketd"
