version: '3'
services:
  sync:
    depends_on:
      - auth
      - rabbitmq
      - websocketd
    environment:
      TARGETS: "auth:9497,rabbitmq:5672,websocketd:9502"

  websocketd:
    volumes:
      - "./etc/xivo-websocketd/conf.d/config.no_mongooseim_server.yml:/etc/xivo-websocketd/conf.d/config.yml"
