version: '3'
services:
  sync:
    depends_on:
      - rabbitmq
      - websocketd
    environment:
      TARGETS: "rabbitmq:5672,websocketd:9502"

  websocketd:
    volumes:
      - "./etc/xivo-websocketd/conf.d/20-wrong-auth-server.yml:/etc/xivo-websocketd/conf.d/20-wrong-auth-server.yml"
