version: '3'
services:
  sync:
    image: waisbrot/wait
    environment:
      TIMEOUT: "15"

  auth:
    image: wazopbx/xivo-auth-mock
    volumes:
      - ./ssl:/usr/local/share/ssl
    ports:
      - "9497"

  mongooseim:
    image: mongooseim/mongooseim:2.1.0
    hostname: mongooseim-1
    expose:
      - 5222
    ports:
      - 8088
    volumes:
      - ./etc/mongooseim:/member
      - ./mongooseim:/tmp/mongooseim

  rabbitmq:
    image: rabbitmq:3.6.6
    ports:
      - "5672"

  websocketd:
    image: xivo-websocketd-test
    volumes:
      - "../..:/usr/src/xivo-websocketd"
      - "./etc/xivo-websocketd:/etc/xivo-websocketd"
      - "./ssl:/usr/local/share/ssl"
      - "./mongooseimctl:/usr/bin/mongooseimctl"
    ports:
      - "9502"
    environment:
      HOME: "/usr/src/xivo-websocketd"
