version: '3'
services:
  sync:
    image: waisbrot/wait
    links:
      - auth
      - mongooseim
      - rabbitmq
      - websocketd
    environment:
      TARGETS: "auth:9497,mongooseim:5222,rabbitmq:5672,websocketd:9502"
      TIMEOUT: "5"

  auth:
    image: p0bailey/docker-flask
    volumes:
      - "./xivo-auth:/usr/local/share/xivo-auth"
      - "./ssl:/usr/local/share/ssl"
    command: "python /usr/local/share/xivo-auth/mock-xivo-auth.py 9497"
    expose:
      - "9497"

  mongooseim:
    image: mongooseim/mongooseim:latest
    hostname: mongooseim-1
    expose:
      - 5222
    volumes:
      - ./etc/mongooseim:/member
      - ./mongooseim:/tmp/mongooseim

  rabbitmq:
    image: rabbitmq:3.6.6
    ports:
      - "5672"

  websocketd:
    image: xivo-websocketd-test
    volumes:
      - "../../..:/usr/src/xivo-websocketd"
      - "./etc/xivo-websocketd:/etc/xivo-websocketd"
      - "./ssl:/usr/local/share/ssl"
    ports:
      - "9502"
    links:
      - auth
      - mongooseim
      - rabbitmq
